stages:
  - build:go
  - build:java
  - build:docker
  - build:deploy

variables:
  GROUP_ID: cn.com.xuxiaowei.gitbot
  ARTIFACT_ID: gitbot
  VERSION: 0.0.1-SNAPSHOT
  CI_JAVA_OPTS: -Xms256m -Xmx512m

include:
  - local: .gitlab/ci/build-go.yml
  - local: .gitlab/ci/build-java.yml
  - local: .gitlab/ci/build-docker.yml
  - local: .gitlab/ci/build-deploy-g150s.yml
