services:
  gitbot:
    image: ${CI_REGISTRY_IMAGE}:${VERSION}-${CI_PIPELINE_ID}
    restart: always
    ports:
      - ${GITBOT_PORT:-45950}:${GITBOT_PORT:-45950}
    volumes:
      - /gitbot/logs:/logs
      - /gitbot/config:/config
    environment:
      - GITBOT_PORT=${GITBOT_PORT:-45950}
      - GITBOT_REDIS_HOST=${GITBOT_REDIS_HOST:-127.0.0.1}
      - GITBOT_REDIS_PORT=${GITBOT_REDIS_PORT:-6379}
      - GITBOT_REDIS_DATABASE=${GITBOT_REDIS_DATABASE:-10}
      - GITBOT_REDIS_PASSWORD=${GITBOT_REDIS_PASSWORD:-xuxiaowei.com.cn}
      - GITBOT_DATABASE_HOST=${GITBOT_DATABASE_HOST:-127.0.0.1}
      - GITBOT_DATABASE_PORT=${GITBOT_DATABASE_PORT:-3306}
      - GITBOT_DATABASE=${GITBOT_DATABASE:-gitbot}
      - GITBOT_DATABASE_USERNAME=${GITBOT_DATABASE_USERNAME:-root}
      - GITBOT_DATABASE_PASSWORD=${GITBOT_DATABASE_PASSWORD:-xuxiaowei.com.cn}
      - GITBOT_SPRINGDOC_OAUTHFLOW_TOKEN_URL=${GITBOT_SPRINGDOC_OAUTHFLOW_TOKEN_URL:-http://127.0.0.1:45950/oauth2/token}
      # 使用容器部署时，此处应该设置为访问容器的地址
      # 如果容器前使用了代理，请填写代理的地址
      - GITBOT_AUTHORIZE_REDIRECT_URI=${GITBOT_AUTHORIZE_REDIRECT_URI:-http://127.0.0.1:45950/login/code}
      - APP_ARGS=${GITBOT_APP_ARGS:-}
    container_name: gitbot
