server:
  port: ${GITBOT_PORT:45950}
  forward-headers-strategy: NATIVE
  tomcat:
    # https://docs.spring.io/spring-boot/how-to/webserver.html#howto.webserver.use-behind-a-proxy-server.tomcat
    remoteip:
      # 从中提取远程IP的HTTP标头的名称。 例如，`X-Forwarded-For`、`X-Real-IP`。
      remote-ip-header: X-Forwarded-For
      # 用于覆盖原始端口值的HTTP标头的名称。
      port-header: X-Forwarded-Proto
  compression:
    # 开启压缩
    enabled: true

---

spring:
  application:
    name: gitbot
---

spring:
  data:
    redis:
      host: ${GITBOT_REDIS_HOST:127.0.0.1}
      port: ${GITBOT_REDIS_PORT:6379}
      database: ${GITBOT_REDIS_DATABASE:10}
      password: ${GITBOT_REDIS_PASSWORD:xuxiaowei.com.cn}

---

spring:
  datasource:
    url: jdbc:p6spy:mysql://${GITBOT_DATABASE_HOST:127.0.0.1}:${GITBOT_DATABASE_PORT:3306}/${GITBOT_DATABASE:gitbot}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ${GITBOT_DATABASE_USERNAME:root}
    password: ${GITBOT_DATABASE_PASSWORD:xuxiaowei.com.cn}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

---

gitbot:
  title: "Git 机器人"
  cmd: gitbot-go

---

gitbot:
  private-key: ${GITBOT_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9QRluemhgJJW943z+Hei4AORfWXn+qlL+9pW5Yw4ylVtaqJXKysvvHw1XSLQ0oF/5R9rRokExi2xEZOwo4a/i6XChQIwOLNnjvEJRUxHokJubepV6N4rkZY9q2tEU9ZfAgvkbieThmSkSEVSfSp4nAQ8bvRA3FkM0lUipsMrQJE5mJ93/tETL1JCMixBtWNSYLYnT0hcTgUrdgMiW1Q4kt/sBKeQhvlqX8h6UosiShhqIjgmPDr/MrZBfA1o7vgVI4hvEMz/KLGuS4Cu2yuotvGPD8EyVbmkuC5N9t5ehtuZL63UyAh8KZbJ7kZcKy65L4r9ESUua8G1P6jXFk0GjAgMBAAECggEACYT7Qv/cPS3J7G3DbULS4GKHGja1eLZXi2Sa3mLZpXi2yiYdtsAhpusAcEoDanxAp5jSLGZFcjkJnp0W9e14O+kzFaFaCiJ+aUKgcVfE2FZhxV3So/2kOl3Ta3QLPUsnMXNFFXoHrcNW+gYuI/8MWnjmqiYF6Udw5PW3XHW8leCPSTL+XREhXvr42WbUdVJx5D0T1Kzxby3RhyM+sOfgnj0ItXeqcAnci7x/KyO7uN3lBYmn7uVluYdh08oB1sJ1/+FZy6CAmW3gR11HhpdSgJcdxmcK53Viv0LAM6zCR3o6YJePD/BB7vDS79OXNJwOX78iQ88demZLQWl8c7KOmQKBgQC//OuOnc9RjRaYqsrr2zPqDNpgw6lS3zSpao/oc1Q0asTH/QGFY/8E9ZYakMotultk2SzwaDUDk0MBxQlIMJUsz1pQHG1JvjESQ33wFyjUW1EGHp9d5EgdQ+QFB3Pnr1M+rSOT8lkMjkvkNsy1TADUSRpDXTQHtmVD91ecvxsR+wKBgQD8WtjdLnJBAtdMTlduh0eS7n8l+dmfz94lWs6QX0GEuHZyExPqHyVyyYje4kQ/8BOThVBJmzwAkbSJnjjY3dKf/aN3jagzUwp53nbcE0cj7Hbokx6WC49aHV7GOe1VxHQ1DLX3uxytICIzy4D3oRtOg2xXfEYNEKHdTXzTQS2meQKBgF9c2QChIH6Ij0XL6DmZS0MhmUNhTPTuC/FvDgZPau8SbaZM5PmF/wFOn32Yl+R44bbJLUpI6LRa7Hivj3m9MAvu/xQ12o87mpJQ1fhw+IXqyec5RL3Vi4CF3XgmCIt3iejjBX4SbesPr2CvW6VeGDdaDGKTpCmEju5gqLMiNecLAoGBAIBJHp2yEtsBurlLyh6iHryPCYwgq4UWgvOyaffytLfnni73i9Qk6UClOzMzC0cFoK4Jw3rns2UGrSSYjoWQnpY+tm78UFlnCZhSg1H1auDUQM6Sm6XjUoiZDajvobtMF1cwkwDQ2g8YmsqB1ZoNCHitTtJalrHllqON1LsAE1jhAoGAUNxiVF4GUu4DrW7Dpbdpocme1b5oj9jDaYXnkRBFYnlrX9vNGy2ctYEWHEIW7LFy374aGVgXFikkRjVxehCuoO+qt2wN/fQScFnQvMOjdRAnpInvCjoi5NfIBtKAU/Co7TgR6ogAFGh2NvTZYUmj9JoQ1Pd6v+1Qrm9Zsqz+vRE=}
  public-key: ${GITBOT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvUEZbnpoYCSVveN8/h3ouADkX1l5/qpS/vaVuWMOMpVbWqiVysrL7x8NV0i0NKBf+Ufa0aJBMYtsRGTsKOGv4ulwoUCMDizZ47xCUVMR6JCbm3qVejeK5GWPatrRFPWXwIL5G4nk4ZkpEhFUn0qeJwEPG70QNxZDNJVIqbDK0CROZifd/7REy9SQjIsQbVjUmC2J09IXE4FK3YDIltUOJLf7ASnkIb5al/IelKLIkoYaiI4Jjw6/zK2QXwNaO74FSOIbxDM/yixrkuArtsrqLbxjw/BMlW5pLguTfbeXobbmS+t1MgIfCmWye5GXCsuuS+K/RElLmvBtT+o1xZNBowIDAQAB}
  token-url: http://127.0.0.1:${GITBOT_PORT:45950}/oauth2/token
  authorize-client-id: ${GITBOT_AUTHORIZE_CLIENT_ID:messaging-client}
  authorize-client-secret: ${GITBOT_AUTHORIZE_CLIENT_SECRET:secret}
  authorize-redirect-uri: ${GITBOT_AUTHORIZE_REDIRECT_URI:http://127.0.0.1:${GITBOT_PORT:45950}/login/code}
  # 请求授权范围，多个值使用空格隔开，请勿将空格转译，代码会自动将空格转译
  authorize-scope: openid profile message.read message.write
  # 开发时，此处使用前端的开发地址，如：http://127.0.0.1:5173
  authorize-success-url: ${GITBOT_AUTHORIZE_SUCCESS_URL:http://127.0.0.1:${GITBOT_PORT:45950}}
  ticket-prefix: "ticket:"
  allowed-origins:
    - http://127.0.0.1:5173
    - http://localhost:5173
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600
  pattern: /**
  save-namespace-redis-key-prefix: ${GITBOT_SAVE_NAMESPACE_REDIS_KEY_PREFIX:save:namespace:}
  save-project-redis-key-prefix: ${GITBOT_SAVE_PROJECT_REDIS_KEY_PREFIX:save:project:}
  save-branch-redis-key-prefix: ${GITBOT_SAVE_BRANCH_REDIS_KEY_PREFIX:save:branch:}
  scheduled:
    enabled-gitlab: ${GITBOT_SCHEDULED_ENABLED_GITLAB:false}
    enabled-github: ${GITBOT_SCHEDULED_ENABLED_GITHUB:false}
    auto-pull-request: ${GITBOT_SCHEDULED_AUTO_PULL_REQUEST:false}

---

springdoc:
  api-docs:
    # 是否开启 API
    # 优先级高于 springdoc.swagger-ui.enabled
    enabled: ${GITBOT_SPRINGDOC_API_DOCS_ENABLED:true}
  swagger-ui:
    # 是否开启 UI
    # 优先级低于 springdoc.api-docs.enabled
    enabled: ${GITBOT_SPRINGDOC_SWAGGER_UI_ENABLED:true}
    default-models-expand-depth: 20
    default-model-expand-depth: 20
    oauth:
      clientId: messaging-client
      clientSecret: secret
  oAuthFlow:
    tokenUrl: ${GITBOT_SPRINGDOC_OAUTHFLOW_TOKEN_URL:http://127.0.0.1:45950/oauth2/token}

---

logging:
  level:
    cn.com.xuxiaowei: debug
    org.springframework.web: debug
    # 当前应用响应数据
    org.springframework.core.codec.CharSequenceEncoder: debug
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{G-Request-Id} %clr(:){faint} %X{G-Host} %clr(:){faint} %X{G-Host-Name} %clr(:){faint} %X{G-Host-Address} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %X{G-Request-Id} : %X{G-Host} : %X{G-Host-Name} : %X{G-Host-Address} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: /logs/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 365
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log.gz
